module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  theme: {
    extend: {},
    fontFamily: {
      Poppins: [
        "Poppins",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
    },
    colors: {
      blue: "#4D47C3",
      red: "#ff0000",
      purpple: "#A7A3FF",
      dark: "#121212",
      light: "#ffffff",
      gray: "#B0B0B0",
      success: "bg-blue-600",
      error: "bg-red-600",
      info: "bg-gray-600",
      warning: "bg-orange-400",
      default: "bg-indigo-600",
      dark: "bg-white-600 font-gray-300",
    },
  },
  plugins: [],
};
